package awareness

import (
	"fmt"
	"os"
	"strings"
)

var agentConfigFiles = []string{"CLAUDE.md", "AGENTS.md", ".cursorrules"}

const awarenessBlock = `
<!-- Generated by virgil init — DO NOT EDIT MANUALLY -->
## Virgil Methodology (auto-configured)

This project uses the Virgil methodology for AI-assisted development.
Methodology docs: .virgil/docs/

### When to activate Virgil

- **Empty/new project** → Read .virgil/docs/overview.md, follow the
  planning phases (idea → spec → design → tasks → handoff)
- **Takeover/onboarding** → Read .virgil/docs/overview.md, run
  ` + "`virgil scan`" + ` to assess current state, follow takeover protocol
- **New feature/change** → Check if planning artifacts exist. If not,
  start from the appropriate phase based on what's known
- **Bug/incident mid-implementation** → Read .virgil/docs/planning/
  behavior/fast-forward.md for the interruption protocol
- **Session close** → Spawn virgil-observer (see below)

### Available CLI commands

- ` + "`virgil init [--tier minimal|standard|full]`" + ` — bootstrap (already done)
- ` + "`virgil scan`" + ` — assess methodology compliance
- ` + "`virgil health`" + ` — project health dashboard
- ` + "`virgil feedback gap|friction|win|session`" + ` — report methodology feedback
- ` + "`virgil feedback report`" + ` — view aggregated feedback

### Key concepts (read the docs for detail)

- **6 artifacts**: idea.md, spec.md, design.md, tasks.md, handoff.md, ops-runbook.md
- **3 actors**: MIM (human, decides), SM (orchestrator, coordinates), Implementors (execute)
- **Execution cycle**: Red → Green → Refactor → Accept
- **The SM never executes** — always delegates to implementors

### Methodology docs index

Read .virgil/docs/README.md for the full index. Start with overview.md.

### Virgil Session Observer

At session close, BEFORE any session summary, spawn a non-interfering subagent:

Role: virgil-observer (fire-and-forget)
Task: Review what happened this session and call:
  - virgil feedback session --goal "..." --docs-used "..." --methodology-grade "A|B|C|D|F"
  - virgil feedback gap --doc "..." --scenario "..." (for each gap found)
  - virgil feedback friction --doc "..." --scenario "..." (for each friction point)
  - virgil feedback win --doc "..." --scenario "..." (for each thing that worked well)

Do NOT interrupt the main workflow. Do NOT wait for results.
<!-- End Virgil auto-configuration -->
`

const sentinelStart = "<!-- Generated by virgil init"

func InjectAwarenessBlock(virgilDir string) (string, error) {
	var targetFile string

	for _, f := range agentConfigFiles {
		if _, err := os.Stat(f); err == nil {
			targetFile = f
			break
		}
	}

	if targetFile == "" {
		targetFile = "CLAUDE.md"
	}

	existing, err := os.ReadFile(targetFile)
	if err == nil && strings.Contains(string(existing), sentinelStart) {
		return targetFile, nil
	}

	f, err := os.OpenFile(targetFile, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)
	if err != nil {
		return "", fmt.Errorf("opening %s: %w", targetFile, err)
	}
	defer f.Close()

	if _, err := f.WriteString(awarenessBlock); err != nil {
		return "", fmt.Errorf("writing awareness block to %s: %w", targetFile, err)
	}

	return targetFile, nil
}
