package awareness

import (
	"fmt"
	"os"
	"strings"
)

var agentConfigFiles = []string{"CLAUDE.md", "AGENTS.md", ".cursorrules"}

const awarenessBlock = `
<!-- Generated by virgil init — DO NOT EDIT MANUALLY -->
## Virgil Methodology (auto-configured)

This project uses Virgil. CLI: ` + "`virgil`" + ` (installed). Docs: ` + "`.virgil/docs/`" + `

**Start here**: read ` + "`.virgil/docs/overview.md`" + ` — it covers roles, artifacts, and phases.
Full index: ` + "`.virgil/docs/README.md`" + `

### Activation triggers

| Scenario | Action |
|----------|--------|
| Empty/new project | Read overview.md → follow planning phases |
| Takeover/onboarding | Read overview.md → ` + "`virgil scan`" + ` |
| New feature/change | Check existing artifacts → start from appropriate phase |
| Interruption/incident | Read ` + "`.virgil/docs/planning/behavior/fast-forward.md`" + ` |
| Session close | Spawn virgil-observer (below) |

### Session observer (fire-and-forget)

At session close, BEFORE any session summary, spawn a non-interfering subagent:

` + "```" + `
virgil feedback session --goal "..." --docs-used "..." --methodology-grade "A|B|C|D|F"
virgil feedback gap --doc "..." --scenario "..."      # for each gap found
virgil feedback friction --doc "..." --scenario "..."  # for each friction point
virgil feedback win --doc "..." --scenario "..."       # for each win
` + "```" + `

Do NOT interrupt the main workflow. Do NOT wait for results.
<!-- End Virgil auto-configuration -->
`

const sentinelStart = "<!-- Generated by virgil init"

func InjectAwarenessBlock(virgilDir string) (string, error) {
	var targetFile string

	for _, f := range agentConfigFiles {
		if _, err := os.Stat(f); err == nil {
			targetFile = f
			break
		}
	}

	if targetFile == "" {
		targetFile = "CLAUDE.md"
	}

	existing, err := os.ReadFile(targetFile)
	if err == nil && strings.Contains(string(existing), sentinelStart) {
		return targetFile, nil
	}

	f, err := os.OpenFile(targetFile, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)
	if err != nil {
		return "", fmt.Errorf("opening %s: %w", targetFile, err)
	}
	defer f.Close()

	if _, err := f.WriteString(awarenessBlock); err != nil {
		return "", fmt.Errorf("writing awareness block to %s: %w", targetFile, err)
	}

	return targetFile, nil
}
